### ISSUE TITLE
RealtimePacketProcessor missing

### ISSUE THREAD

**Issue by Inumedia** [diamondo25/MapleShark#22]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS2001	Source file 'C:\Users\inume\Documents\GitHub\MapleShark\Tools\RealtimePacketProcessor.cs' could not be found.	MapleShark	C:\Users\inume\Documents\GitHub\MapleShark\CSC	1	Active

![image](https://cloud.githubusercontent.com/assets/856822/23840412/5a96ef18-077b-11e7-8a70-1f93c1b5c911.png)

**Comment by WindProphet** [comment]
I found the same problem using Xamarin Studio
           
```
/Library/Frameworks/Mono.framework/Versions/4.8.0/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets` (CoreCompile target) ->

	CSC: error CS2001: Source file `Tools/RealtimePacketProcessor.cs' could not be found
```
