### ISSUE TITLE
Dependencies not resolving correctly

### ISSUE THREAD

**Issue by Inumedia** [diamondo25/MapleShark#23]
The dependencies PacketDotnet and SharpPcap are not being resolved correctly when doing a fresh build on a fresh system

**Comment by Inumedia** [comment]
![image](https://cloud.githubusercontent.com/assets/856822/23840447/9a3301f2-077b-11e7-9aa9-94b3928f0c08.png)

**Comment by Togain** [comment]
You need to update them.

Right click References > Manage NuGet Packages...

**Comment by Togain** [comment]
For anyone wondering, you need to update them.

Right click References > Manage NuGet Packages...

**Comment by Inumedia** [comment]
Nah, updating them changes their version. Which could break stuff.

**Comment by Alex-0000** [comment]
@Inumedia If you try to uninstall the two packages from NuGet it doesn't even let you because it can't find the files for the packages. So that's the problem they need to get reinstalled.
