### ISSUE TITLE
It doesn't show inbound packets.

### ISSUE THREAD

**Issue by IL4AI** [diamondo25/MapleShark#28]
_expectedDataSize is always greater than mCursor.

When receive inbound packet and read the inbound packet, the value of mCursor doesn't change.
_expectedDataSize: 8147
mCursor: 50??

How can I fix both variable?

Outbound is good.

**Comment by Souna** [comment]
https://github.com/Razzstep/MapleShark-GMS-212

You might get help if you open an issue in this repo instead

**Comment by IL4AI** [comment]
thanks
